### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by bluetyson** [globality-corp/sklearn-hierarchical-classification#12]
Traceback (most recent call last):
  File "hier.py", line 14, in <module>
    from sklearn_hierarchical_classification.tests.fixtures import make_digits_dataset
ModuleNotFoundError: No module named 'sklearn_hierarchical_classification.tests'

Hi, just installed and made 'hier.py' from the example.

**Comment by adamhadani** [comment]
@bluetyson I can't reproduce this, please make sure you follow these steps:

1. Create a new virtualenv e.g. `mkvirtualenv myvenv` if using [virtualenvwrapper](https://virtualenvwrapper.readthedocs.io/en/latest/)
2. Install the package locally into it, e.g. in the root directory of checked out repo can run `pip install -e .`
3. Should then be able to import as you did above. I tried using IPython:

```python
In [1]: from sklearn_hierarchical_classification.tests.fixtures import make_digits_dataset

In [2]:
```

**Comment by ndukh** [comment]
Hello. Cannot run examples on google colab (python 3.6, see [notebook](https://colab.research.google.com/drive/1JR9Y92LWOcsNf5z9oRns9vF90hzSNDkq)).
I have tried different ways of installation.
`!pip install sklearn_hierarchical_classification` results in
`ImportError: cannot import name 'multi_labeled'` (as you can see it imports other submodules successfully)
And suggested above
`!git clone https://github.com/globality-corp/sklearn-hierarchical-classification.git shc; cd shc; pip install -e .` leads to
`ModuleNotFoundError: No module named 'sklearn_hierarchical_classification'` (even worse: it can't find the module at all)

**Comment by fbenites** [comment]
Hi,

In colab you need to restart your runtime (it installed the packages but did not update the cache).
I had the same error, and after restart it worked.

**Comment by OleksiyAnokhin** [comment]
Have the same error in 2021 on Colab

`ModuleNotFoundError: No module named 'sklearn_hierarchical_classification.tests'`

Restarted the notebook, but no luck.
