### ISSUE TITLE
Exporting docs to read the docs (or equivalent)

### ISSUE THREAD

**Issue by gpkc** [globality-corp/sklearn-hierarchical-classification#13]
Is there a reason for the package not to have an online docs website, such as read the docs? You already have circleci integration, so pushing to one of those websites should not be too hard. Let me know if you want help with that.

**Comment by adamhadani** [comment]
@gpkc thanks - I did mean to do that, just never got to it. If you have some experience with setting this up please feel free to share steps here and I'll give it a shot. I may get to it before I hear back too if time permits.. will update on this ticket

**Comment by adamhadani** [comment]
@gpkc ended up figuring it out, docs are now published to github pages, available [here](http://code.globality.com/sklearn-hierarchical-classification/).

Added link to README as well.
