### ISSUE TITLE
No module named 'sklearn_hierarchical_classification', after successfully installation by pip

### ISSUE THREAD

**Issue by singhajeet13** [globality-corp/sklearn-hierarchical-classification#16]
After successfully installation by pip, while importing in jupyter notebook, I am getting error-
No module named 'sklearn_hierarchical_classification',

Pip installation message(jupyter notebook instance and installation in the same env)- 
pip install sklearn-hierarchical-classification
Requirement already satisfied: sklearn-hierarchical-classification in ./anaconda3/envs/tensorflow/lib/python3.5/site-packages (1.0.0)
Requirement already satisfied: scipy>=0.19.1 in ./.local/lib/python3.5/site-packages (from sklearn-hierarchical-classification) (1.2.0)
Requirement already satisfied: six>=1.10.0 in ./.local/lib/python3.5/site-packages (from sklearn-hierarchical-classification) (1.12.0)
Requirement already satisfied: networkx>=2.0 in ./anaconda3/envs/tensorflow/lib/python3.5/site-packages (from sklearn-hierarchical-classification) (2.2)
Requirement already satisfied: scikit-learn>=0.19.0 in ./.local/lib/python3.5/site-packages (from sklearn-hierarchical-classification) (0.20.2)
Requirement already satisfied: numpy>=1.13.1 in ./.local/lib/python3.5/site-packages (from sklearn-hierarchical-classification) (1.15.4)
Requirement already satisfied: decorator>=4.3.0 in ./anaconda3/envs/tensorflow/lib/python3.5/site-packages (from networkx>=2.0->sklearn-hierarchical-classification) (4.3.0)

**Comment by piercefreeman** [comment]
Hi @singhajeet13 - I tried to duplicate the issue that you're seeing but it works fine within my Jupyter Notebook.  Are you using a custom virtualenv as your kernel?  Have you tried installing another third party library and seeing if that works?

**Comment by adamhadani** [comment]
Sounds like user error on installation / usage part - closing as wont fix
