### ISSUE TITLE
Cannot install with pip

### ISSUE THREAD

**Issue by YannDubs** [globality-corp/sklearn-hierarchical-classification#2]
Hi,

It seems that `pip install sklearn-hierarchical-classification` doesn't work. tested on python 2 and 3, and I use a mac (although this shouldn't be relevant).

output :
```
Collecting sklearn-hierarchical-classification
  Could not find a version that satisfies the requirement sklearn-hierarchical-classification (from versions: )
No matching distribution found for sklearn-hierarchical-classification
```

Cheers

**Comment by yuedeji** [comment]
Hi,

I met the same problem. Did you get any luck to solve this?

Best,
Yuede

**Comment by YannDubs** [comment]
Hey, I just installed from source.

**Comment by yuedeji** [comment]
Good for you! But could you explain the details? I'm a little bit confused.

**Comment by YannDubs** [comment]
```bash
git clone https://github.com/globality-corp/sklearn-hierarchical-classification.git
cd sklearn-hierarchical-classification
pip install .
```

**Comment by yuedeji** [comment]
It woks! Thanks so much!

**Comment by silentsnooc** [comment]
Installing from pip is not working for me either.

**Comment by moshez** [comment]
It should be working now.

**Comment by moshez** [comment]
https://pypi.org/project/sklearn-hierarchical-classification/1.0.0/
