### ISSUE TITLE
Please update version in PyPI

### ISSUE THREAD

**Issue by masakiaota** [globality-corp/sklearn-hierarchical-classification#21]
If using `pip install`, version 1.0.0 (Jul 31, 2018) will be installed.
I think this version is outdated. People who install this package by `pip`  cannot run examples. (Because of import error on `multi_labeled`)
Therefore, I'd like ask for you to update.

**Comment by adamhadani** [comment]
thanks for the feedback @masakiaota - I just pushed the updated version (1.1.0) to PyPI.
