### ISSUE TITLE
 not enough training data available to train, classification in branch will terminate at node

### ISSUE THREAD

**Issue by yongzhuo** [globality-corp/sklearn-hierarchical-classification#26]
when training, errors as follow:
_train_local_classifier() - not enough training data available to train, classification in branch will terminate at node -1
_train_local_classifier() - not enough training data available to train, classification in branch will terminate at node 
_recursive_predict
clf = self.graph_.node[root][CLASSIFIER]
KeyError: 'classifier'

**Comment by hacktuarial** [comment]
Can you please follow [this issue template](https://github.com/scikit-learn/scikit-learn/blob/master/ISSUE_TEMPLATE.md)? In particular, the steps/code to reproduce this issue will be useful.

**Comment by adamhadani** [comment]
closing as not informative or actionable - if this bug was similar to #31 please try again with release `1.3.0` as I've addressed that issue in #32 . Otherwise please re-open with more verbose information and example of how to reproduce, similar to #31 format (thanks @hacktuarial !)
