### ISSUE TITLE
question on hierarchical classification

### ISSUE THREAD

**Issue by ahorvath** [globality-corp/sklearn-hierarchical-classification#35]
Dear Developers,

I would like to use your package for taxonomic classification. Can you explain me, please, to what extent this approach improves a simple "flat classification" approach? 

Many thanks for your effort.

Bests, 
Attila

**Comment by ahorvath** [comment]
For example, can the hierarchical classification give a non-leaf node?

**Comment by adamhadani** [comment]
@ahorvath - please see documentation and referenced articles for this: http://code.globality.com/sklearn-hierarchical-classification/build/html/index.html

The answer to your second question (non-leaf node prediction) is generally yes
